Assignment 2 — E-Commerce Sales Analysis

Dataset
ecommerce_orders_raw.csv
Objective
You are a data analyst for an e-commerce company. The company wants to understand its customers,
products, sales performance, and revenue trends. Use Pandas to transform the raw order data into
meaningful business information.

Part A — Data Understanding
1. Load the dataset.

In [17]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('../data/ecommerce_orders_raw.csv')
df.head()

,Order_ID,Customer_ID,City,Product_Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Order_Date,Rating
0,O014846,C00722,Delhi,Home Appliances,Mixer,2,10042.08,10,Debit Card,2026-07-25 02:03:50.895393024,4.0
1,O014121,C01623,Pune,Books,Novel,1,34791.00,15,Debit Card,2026-06-27 05:51:34.526301752,1.0
2,O014861,C01543,Hyderabad,Home Appliances,Mixer,2,15693.00,15,Net Banking,2026-07-25 15:53:20.613374224,4.0
3,O000885,C02287,Mumbai,Books,Biography,5,72700.86,20,Debit Card,2025-02-03 22:44:55.379691979,3.0
4,O000412,C00051,Mumbai,Beauty,Shampoo,5,89712.89,25,UPI,2025-01-16 18:48:10.272684845,5.0

In [18]:
#2. Display its structure and dimensions.
df.shape

(15100, 11)

In [19]:
#3. Identify the data types of all columns.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15100 entries, 0 to 15099
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          15100 non-null  object
 1   Customer_ID       15100 non-null  object
 2   City              15100 non-null  object
 3   Product_Category  15100 non-null  object
 4   Product           15100 non-null  object
 5   Quantity          15100 non-null  int64
 6   Unit_Price        15100 non-null  float64
 7   Discount          15100 non-null  int64
 8   Payment_Method    15100 non-null  object
 9   Order_Date        15100 non-null  object
 10  Rating            14699 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 1.3+ MB

In [20]:
#4. Identify missing values.
df.isnull().sum()

Order_ID              0
Customer_ID           0
City                  0
Product_Category      0
Product               0
Quantity              0
Unit_Price            0
Discount              0
Payment_Method        0
Order_Date            0
Rating              401
dtype: int64

In [21]:
#5. Identify duplicate orders.
df.duplicated().sum()

np.int64(100)

6. Examine the unique values in:
o City
o Product Category
o Payment Method

In [22]:
print(df['City'].unique())
df['City'] = df['City'].str.strip().str.title()
print(df['City'].unique())

#product category column
print(df['Product_Category'].unique())

#payment method column
print(df['Payment_Method'].unique())

['Delhi' 'Pune' 'Hyderabad' 'Mumbai' 'Kolkata' 'Bangalore' ' chennai '
 'Chennai' 'Coimbatore' 'CHENNAI']
['Delhi' 'Pune' 'Hyderabad' 'Mumbai' 'Kolkata' 'Bangalore' 'Chennai'
 'Coimbatore']
['Home Appliances' 'Books' 'Beauty' 'Sports' 'Clothing' 'Electronics']
['Debit Card' 'Net Banking' 'UPI' 'Credit Card' 'Cash on Delivery']

Part B — Data Cleaning
7. Handle missing ratings.

In [23]:
print("No of missing values in Rating column:", df['Rating'].isna().sum())
print("Unique values in Rating column:", df['Rating'].unique())

df['Rating'].fillna(df['Rating'].median(), inplace=True)
df['Rating'] = df['Rating'].astype(int)
df['Rating'].unique()

No of missing values in Rating column: 401
Unique values in Rating column: [ 4.  1.  3.  5.  2. nan]

/var/folders/0f/pwtnxcjd59gb4c95ngqx5rq80000gn/T/ipykernel_32876/2125279031.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].median(), inplace=True)

array([4, 1, 3, 5, 2])

8. Standardize city names.

In [24]:
df['City'].unique()

array(['Delhi', 'Pune', 'Hyderabad', 'Mumbai', 'Kolkata', 'Bangalore',
       'Chennai', 'Coimbatore'], dtype=object)

In [28]:
#9. Identify invalid quantities.
print(df['Quantity'].unique())
df['Quantity'] = df['Quantity'].astype(int)
print(df['Quantity'].unique())
df[df['Quantity'] < 0]
#Quntity will not be in negative value so it will be positive value. So we will replace the negative values with positive values using abs() function.
df['Quantity'] = df['Quantity'].abs()
print(df['Quantity'].unique())

[ 2  1  5  3  4 -2]
[ 2  1  5  3  4 -2]
[2 1 5 3 4]

In [29]:
#10. Handle duplicate orders.

print("Number of duplicate orders removed:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("Number of duplicate orders after removal:", df.duplicated().sum())

Number of duplicate orders removed: 100
Number of duplicate orders after removal: 0

In [36]:
#11. Convert Order_Date into an appropriate datetime format.

df['Order_Date'] = df['Order_Date'].astype('datetime64[ns]')
df['Order_Date'] = df['Order_Date'].dt.strftime('%Y-%m-%d')
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Order_Date'].head()

0   2026-07-25
1   2026-06-27
2   2026-07-25
3   2025-02-03
4   2025-01-16
Name: Order_Date, dtype: datetime64[ns]

Part C — Feature Engineering
12. Create:
Gross_Amount = Quantity × Unit_Price

In [39]:
df['Gross_Amount'] = df['Quantity'].astype(int) * df['Unit_Price'].astype(float)
df['Gross_Amount'].head()

0     20084.16
1     34791.00
2     31386.00
3    363504.30
4    448564.45
Name: Gross_Amount, dtype: float64

In [ ]:
df['Unit_Price']

13. Create:
Discount_Amount = Gross_Amount × Discount / 100

In [41]:
df['Discount_Amount'] = (df['Gross_Amount'] * (df['Discount'].astype(float) / 100)).round(2)
df['Discount_Amount'].head()

0      2008.42
1      5218.65
2      4707.90
3     72700.86
4    112141.11
Name: Discount_Amount, dtype: float64

14. Create:
Net_Amount = Gross_Amount - Discount_Amount

In [42]:
df['Net_Amount'] = df['Gross_Amount'] - df['Discount_Amount']
df['Net_Amount'] = df['Net_Amount'].round(2)
df['Net_Amount'].head()

0     18075.74
1     29572.35
2     26678.10
3    290803.44
4    336423.34
Name: Net_Amount, dtype: float64

15. Create a Rating_Category column:
1–2 → Poor
3 → Average
4 → Good
5 → Excellent

In [44]:
df['Rating'].head()
mapping = {1: 'Poor', 2: 'Fair', 3: 'Good', 4: 'Very Good', 5: 'Excellent'}
df['Rating_Category'] = df['Rating'].map(mapping)
df['Rating_Category'].head()

0    Very Good
1         Poor
2    Very Good
3         Good
4    Excellent
Name: Rating_Category, dtype: object

16. Extract the following from Order_Date:
• Year
• Month
• Day
• Day of Week

In [46]:
df['Order_Date'].head()
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
df['Day'] = df['Order_Date'].dt.day
df['Dayof_Week'] = df['Order_Date'].dt.day_name()
df[['Order_Date', 'Year', 'Month', 'Day', 'Dayof_Week']].head()

  Order_Date  Year  Month  Day Dayof_Week
0 2026-07-25  2026      7   25   Saturday
1 2026-06-27  2026      6   27   Saturday
2 2026-07-25  2026      7   25   Saturday
3 2025-02-03  2025      2    3     Monday
4 2025-01-16  2025      1   16   Thursday

Part D — Business Analysis

In [49]:
#17. Calculate total revenue.
total_revenue = df['Net_Amount'].sum().round(2)
print("Total Revenue: ", total_revenue)

Total Revenue:  1982836646.07

In [50]:
#18. Calculate total number of orders.
total_orders = df['Order_ID'].nunique()
print("Total Number of Orders: ", total_orders)

Total Number of Orders:  15000

In [51]:
#19. Find the average order value.
average_order_value = total_revenue / total_orders
print("Average Order Value: ", average_order_value.round(2))

Average Order Value:  132189.11

In [52]:
#20. Find total revenue by product category.
total_revenue_by_category = df.groupby('Product_Category')['Net_Amount'].sum().round(2)
print("Total Revenue by Product Category:")
print(total_revenue_by_category)

Total Revenue by Product Category:
Product_Category
Beauty             3.311914e+08
Books              3.329584e+08
Clothing           3.457054e+08
Electronics        3.239196e+08
Home Appliances    3.193052e+08
Sports             3.297568e+08
Name: Net_Amount, dtype: float64

In [55]:
df.columns

Index(['Order_ID', 'Customer_ID', 'City', 'Product_Category', 'Product',
       'Quantity', 'Unit_Price', 'Discount', 'Payment_Method', 'Order_Date',
       'Rating', 'Gross_Amount', 'Discount_Amount', 'Net_Amount',
       'Rating_Category', 'Year', 'Month', 'Day', 'Dayof_Week'],
      dtype='object')

In [56]:
#21. Find the top 10 products by revenue.
top_10_products = df.groupby('Product')['Net_Amount'].sum().round(2).nlargest(10)
print("Top 10 Products by Revenue:")
print(top_10_products)

Top 10 Products by Revenue:
Product
Jeans         93683575.07
Jacket        88865097.19
Self Help     88432733.50
Yoga Mat      88323335.24
Shampoo       88286816.62
Skin Serum    87182348.18
Laptop        86973276.62
Mixer         85426681.43
Headphones    83621256.36
Textbook      83477808.52
Name: Net_Amount, dtype: float64

In [57]:
#2. Find the city generating the highest revenue.
highest_revenue_city = df.groupby('City')['Net_Amount'].sum().round(2).nlargest(1)
print("City generating the highest revenue:")
print(highest_revenue_city)

City generating the highest revenue:
City
Chennai    2.859610e+08
Name: Net_Amount, dtype: float64

In [59]:
df['Payment_Method'].value_counts()

Payment_Method
Debit Card          3062
Cash on Delivery    3057
Credit Card         2998
UPI                 2952
Net Banking         2931
Name: count, dtype: int64

In [58]:
#23. Find the most frequently used payment method.
most_frequent_payment_method = df['Payment_Method'].value_counts().idxmax()
print("Most Frequently Used Payment Method:")
print(most_frequent_payment_method)

Most Frequently Used Payment Method:
Debit Card

In [60]:
#24. Find the average rating for each product category.
average_rating_by_category = df.groupby('Product_Category')['Rating'].mean().round(2)
print("Average Rating by Product Category:")
print(average_rating_by_category)

Average Rating by Product Category:
Product_Category
Beauty             3.90
Books              3.85
Clothing           3.91
Electronics        3.83
Home Appliances    3.85
Sports             3.88
Name: Rating, dtype: float64

In [63]:
#25. Calculate monthly revenue.
monthly_revenue = df.groupby(df['Order_Date'].dt.to_period('M'))['Net_Amount'].sum().round(2)
print("Monthly Revenue:")
print(monthly_revenue)

Monthly Revenue:
Order_Date
2025-01    1.081087e+08
2025-02    9.685231e+07
2025-03    1.059993e+08
2025-04    1.074172e+08
2025-05    1.063948e+08
2025-06    1.025567e+08
2025-07    1.074132e+08
2025-08    1.072570e+08
2025-09    1.084266e+08
2025-10    1.088753e+08
2025-11    1.051700e+08
2025-12    1.034943e+08
2026-01    1.108373e+08
2026-02    9.477007e+07
2026-03    1.015996e+08
2026-04    9.976139e+07
2026-05    1.064280e+08
2026-06    9.943392e+07
2026-07    1.020410e+08
Freq: M, Name: Net_Amount, dtype: float64

In [64]:
#26. Identify the highest-revenue month.
highest_revenue_month = monthly_revenue.idxmax()
print("Highest Revenue Month:", highest_revenue_month)

Highest Revenue Month: 2026-01

In [65]:
#27. Find the top 10 customers by total spending.
top_10_customers = df.groupby('Customer_ID')['Net_Amount'].sum().round(2).nlargest(10)
print("Top 10 Customers by Total Spending:")
print(top_10_customers)

Top 10 Customers by Total Spending:
Customer_ID
C01527    2398927.85
C01856    2352195.04
C02170    2179011.48
C01626    2177251.92
C01882    2104829.44
C00990    2057788.91
C02988    2009290.05
C02588    2002666.45
C00139    1988372.54
C00944    1971526.55
Name: Net_Amount, dtype: float64

In [67]:
df.columns

Index(['Order_ID', 'Customer_ID', 'City', 'Product_Category', 'Product',
       'Quantity', 'Unit_Price', 'Discount', 'Payment_Method', 'Order_Date',
       'Rating', 'Gross_Amount', 'Discount_Amount', 'Net_Amount',
       'Rating_Category', 'Year', 'Month', 'Day', 'Dayof_Week'],
      dtype='object')

In [66]:
#28. Compare revenue generated by different cities.
revenue_by_city = df.groupby('City')['Net_Amount'].sum().round(2)
print("Revenue by City:")
print(revenue_by_city)

Revenue by City:
City
Bangalore     2.399458e+08
Chennai       2.859610e+08
Coimbatore    2.462794e+08
Delhi         2.463109e+08
Hyderabad     2.328486e+08
Kolkata       2.394204e+08
Mumbai        2.479485e+08
Pune          2.441221e+08
Name: Net_Amount, dtype: float64

In [72]:
#29. Find which product category has the highest average order value.
average_order_value_by_category = df.groupby('Product_Category')['Net_Amount'].mean().round(2)
highest_avg_order_value_category = average_order_value_by_category.idxmax()
print("Product Category with Highest Average Order Value:")
print(highest_avg_order_value_category, "with an average order value of", average_order_value_by_category[highest_avg_order_value_category])

Product Category with Highest Average Order Value:
Clothing with an average order value of 135252.49