Assignment 3 — IoT Sensor Data Analysis
Dataset
iot_sensor_data_raw.csv
Objective
You are working as an IoT data analyst for a manufacturing company.
The company has multiple sensors installed across factories. Your task is to analyze the sensor data
and identify abnormal operating conditions.

Part A — Data Preparation
1. Load the dataset.

In [16]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('../data/iot_sensor_data_raw.csv')
df.head()

,Timestamp,Device_ID,Temperature,Humidity,Pressure,Vibration,Battery_Level,Location,Machine_Status
0,2026-04-21 22:30:00,DEV_005,65.89,62.70,1007.96,2.22,46.51,Factory_A,Warning
1,2026-01-22 06:15:00,DEV_007,70.65,70.95,1021.85,2.73,57.04,Factory_A,Normal
2,2026-04-01 07:00:00,DEV_005,81.01,60.49,1009.82,2.15,11.65,Factory_A,Normal
3,2026-01-12 14:30:00,DEV_007,74.17,68.76,1001.42,2.03,17.36,Factory_C,Critical
4,2026-05-25 19:30:00,DEV_008,74.04,54.32,1014.34,NaN,27.04,Factory_C,Normal

In [17]:
#2. Display its dimensions and structure.
df.shape

(20000, 9)

In [18]:
#3. Convert Timestamp into Pandas datetime.
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [19]:
#4. Check whether the timestamps are correctly ordered.
df = df.sort_values(by='Timestamp')
df.head()

,Timestamp,Device_ID,Temperature,Humidity,Pressure,Vibration,Battery_Level,Location,Machine_Status
3149,2026-01-01 00:00:00,DEV_007,50.97,65.59,990.96,1.94,99.73,Factory_C,Normal
13592,2026-01-01 00:15:00,DEV_004,67.31,33.98,1021.80,2.48,50.16,Factory_B,Normal
16379,2026-01-01 00:30:00,DEV_005,78.07,62.70,1029.55,2.86,63.12,Factory_A,Normal
1204,2026-01-01 00:45:00,DEV_007,70.26,51.49,994.29,3.20,71.38,Factory_B,Normal
13102,2026-01-01 01:00:00,DEV_003,79.59,59.03,997.97,2.04,66.31,Factory_C,Normal

In [20]:
#5. Identify missing sensor readings.
df.isnull().sum()

Timestamp           0
Device_ID           0
Temperature       299
Humidity          300
Pressure          300
Vibration         298
Battery_Level       0
Location            0
Machine_Status      0
dtype: int64

In [21]:
#6. Calculate the percentage of missing values for each sensor.
(df.isnull().sum() / len(df)) * 100

Timestamp         0.000
Device_ID         0.000
Temperature       1.495
Humidity          1.500
Pressure          1.500
Vibration         1.490
Battery_Level     0.000
Location          0.000
Machine_Status    0.000
dtype: float64

Part B — Data Cleaning
7. Handle missing sensor values using an appropriate method.

In [22]:
print(df['Temperature'].mean().round(2))
print(df['Temperature'].median().round(2))

70.22
70.04

In [23]:
print(df['Humidity'].mean().round(2))
print(df['Humidity'].median().round(2))

55.0
54.99

In [24]:
print(df['Pressure'].mean().round(2))
print(df['Pressure'].median().round(2))

1012.89
1012.79

In [25]:
print(df['Vibration'].mean().round(2))
print(df['Vibration'].median().round(2))

2.53
2.5

In [26]:
df['Temperature'].fillna(df['Temperature'].mean().round(2), inplace=True)
df['Humidity'].fillna(df['Humidity'].mean().round(2), inplace=True)
df['Pressure'].fillna(df['Pressure'].mean().round(2), inplace=True)
df['Vibration'].fillna(df['Vibration'].mean().round(2), inplace=True)

/var/folders/0f/pwtnxcjd59gb4c95ngqx5rq80000gn/T/ipykernel_34743/3190887596.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Temperature'].fillna(df['Temperature'].mean().round(2), inplace=True)
/var/folders/0f/pwtnxcjd59gb4c95ngqx5rq80000gn/T/ipykernel_34743/3190887596.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Humidity'].fillna(df['Humidity'].mean().round(2), inplace=True)
/var/folders/0f/pwtnxcjd59gb4c95ngqx5rq80000gn/T/ipykernel_34743/3190887596.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Pressure'].fillna(df['Pressure'].mean().round(2), inplace=True)
/var/folders/0f/pwtnxcjd59gb4c95ngqx5rq80000gn/T/ipykernel_34743/3190887596.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Vibration'].fillna(df['Vibration'].mean().round(2), inplace=True)

In [27]:
df.isna().sum()

Timestamp         0
Device_ID         0
Temperature       0
Humidity          0
Pressure          0
Vibration         0
Battery_Level     0
Location          0
Machine_Status    0
dtype: int64

In [28]:
#8. Identify abnormal temperature readings.
df[df['Temperature'] > df['Temperature'].quantile(0.99)]

,Timestamp,Device_ID,Temperature,Humidity,Pressure,Vibration,Battery_Level,Location,Machine_Status
16495,2026-01-01 21:30:00,DEV_006,89.090000,68.37,1043.35,2.18,94.88,Factory_A,Warning
8665,2026-01-02 04:30:00,DEV_007,90.480000,26.54,992.67,2.67,74.96,Factory_C,Normal
16228,2026-01-02 16:00:00,DEV_007,93.260000,39.59,1012.75,2.51,86.07,Factory_C,Normal
14322,2026-01-04 04:15:00,DEV_005,90.420000,55.00,1015.33,3.23,71.90,Factory_A,Normal
7751,2026-01-04 04:30:00,DEV_004,91.560000,36.62,979.59,2.44,79.24,Factory_B,Normal
...,...,...,...,...,...,...,...,...,...
15829,2026-07-24 03:30:00,DEV_004,93.930000,51.67,1007.89,2.04,39.42,Factory_A,Normal
8062,2026-07-25 09:45:00,DEV_005,129.171923,45.91,999.23,2.10,53.12,Factory_C,Normal
16012,2026-07-25 17:00:00,DEV_002,127.803728,55.00,1015.94,3.49,20.30,Factory_B,Normal
8842,2026-07-26 05:45:00,DEV_005,93.130000,58.78,1018.99,2.79,92.37,Factory_C,Normal
18733,2026-07-27 03:30:00,DEV_004,92.400000,46.18,1024.67,2.69,87.57,Factory_C,Normal

In [29]:
#9. Identify abnormal vibration readings.
df[df['Vibration'] > df['Vibration'].quantile(0.99)]

,Timestamp,Device_ID,Temperature,Humidity,Pressure,Vibration,Battery_Level,Location,Machine_Status
17439,2026-01-03 00:15:00,DEV_007,79.25,51.09,1011.11,4.980000,12.22,Factory_A,Normal
9591,2026-01-03 15:15:00,DEV_005,73.20,57.12,1036.41,5.270000,42.50,Factory_C,Normal
8457,2026-01-04 08:15:00,DEV_005,62.51,39.78,1022.83,4.820000,89.53,Factory_A,Normal
12556,2026-01-04 16:30:00,DEV_008,62.14,59.09,1025.14,4.430000,97.42,Factory_C,Normal
3719,2026-01-04 17:45:00,DEV_003,70.22,53.40,981.82,4.430000,78.97,Factory_A,Normal
...,...,...,...,...,...,...,...,...,...
18299,2026-07-24 18:45:00,DEV_002,88.23,46.12,1027.67,14.646599,94.75,Factory_A,Warning
13555,2026-07-25 12:00:00,DEV_006,68.70,20.80,1030.45,4.780000,70.31,Factory_C,Normal
12140,2026-07-27 00:00:00,DEV_006,68.83,56.53,1013.79,4.810000,36.16,Factory_B,Normal
16330,2026-07-27 02:00:00,DEV_001,38.31,49.35,992.96,4.790000,36.01,Factory_A,Normal
15144,2026-07-27 09:15:00,DEV_008,70.38,47.01,1015.04,4.670000,27.97,Factory_C,Warning

In [30]:
#10. Identify machines with critically low battery levels.
df[df['Battery_Level'] < df['Battery_Level'].quantile(0.01)]

,Timestamp,Device_ID,Temperature,Humidity,Pressure,Vibration,Battery_Level,Location,Machine_Status
8569,2026-01-01 23:00:00,DEV_002,83.24,53.64,983.25,1.84,10.250000,Factory_C,Normal
4046,2026-01-02 00:45:00,DEV_005,81.50,53.90,1009.08,2.40,10.120000,Factory_C,Normal
17166,2026-01-03 21:00:00,DEV_001,70.79,25.50,993.31,3.61,10.040000,Factory_A,Normal
2830,2026-01-03 23:15:00,DEV_003,78.40,47.97,1012.89,3.16,10.390000,Factory_B,Warning
10765,2026-01-10 02:15:00,DEV_001,83.49,37.97,1011.33,2.74,10.590000,Factory_B,Normal
...,...,...,...,...,...,...,...,...,...
794,2026-07-26 15:30:00,DEV_002,84.24,33.33,1008.65,1.73,10.130000,Factory_C,Normal
6707,2026-07-26 18:00:00,DEV_002,72.10,66.65,1043.41,2.25,10.460000,Factory_C,Normal
264,2026-07-27 00:30:00,DEV_005,68.40,64.55,1041.01,0.71,10.020000,Factory_C,Normal
2750,2026-07-27 11:30:00,DEV_004,60.39,40.77,1020.17,3.77,10.500000,Factory_A,Normal
6648,2026-07-27 16:45:00,DEV_002,87.29,47.59,1019.42,1.24,10.186017,Factory_A,Normal

In [31]:
#11. Explain how you decided what constitutes an abnormal reading.
# For temperature readings, I used the 99th percentile as the threshold for abnormal readings.
# For vibration readings, I used the 99th percentile as the threshold for abnormal readings.
# For battery level readings, I used the 1st percentile as the threshold for critically low battery levels.

In [32]:
#12. Calculate the average temperature by hour.
df.groupby(df['Timestamp'].dt.hour)['Temperature'].mean()

Timestamp
0     70.085449
1     70.545657
2     69.927763
3     69.719553
4     69.810849
5     70.266341
6     70.252045
7     70.650541
8     70.392388
9     70.974838
10    69.933608
11    69.895241
12    69.996790
13    70.129707
14    69.841060
15    70.223374
16    69.968989
17    70.548722
18    70.223594
19    70.000337
20    70.136558
21    70.142308
22    71.173567
23    70.405397
Name: Temperature, dtype: float64

In [33]:
#13. Calculate the average temperature for each device.
df.groupby('Device_ID')['Temperature'].mean()

Device_ID
DEV_001    70.251258
DEV_002    70.373472
DEV_003    69.937686
DEV_004    70.578802
DEV_005    70.119169
DEV_006    70.008439
DEV_007    70.148511
DEV_008    70.318724
Name: Temperature, dtype: float64

In [34]:
#14. Calculate the average vibration for each device.
df.groupby('Device_ID')['Vibration'].mean()

Device_ID
DEV_001    2.553211
DEV_002    2.564050
DEV_003    2.538903
DEV_004    2.524846
DEV_005    2.494709
DEV_006    2.553734
DEV_007    2.521457
DEV_008    2.528587
Name: Vibration, dtype: float64

In [35]:
#5. Find the maximum temperature recorded by each device.
df.groupby('Device_ID')['Temperature'].max()

Device_ID
DEV_001    159.746758
DEV_002    151.818550
DEV_003    157.603693
DEV_004    151.965273
DEV_005    152.974450
DEV_006    136.003203
DEV_007    153.877632
DEV_008    153.622123
Name: Temperature, dtype: float64

In [36]:
#16. Find the minimum battery level for each device.
df.groupby('Device_ID')['Battery_Level'].min()

Device_ID
DEV_001    2.257059
DEV_002    2.154615
DEV_003    3.670604
DEV_004    8.514009
DEV_005    2.956738
DEV_006    2.201033
DEV_007    2.146086
DEV_008    2.011730
Name: Battery_Level, dtype: float64

In [37]:
#17. Determine which device has the highest average vibration.
df.groupby('Device_ID')['Vibration'].mean().idxmax()

'DEV_002'

In [39]:
df.columns

Index(['Timestamp', 'Device_ID', 'Temperature', 'Humidity', 'Pressure',
       'Vibration', 'Battery_Level', 'Location', 'Machine_Status'],
      dtype='object')

In [40]:
#18. Determine which factory has the highest average temperature.
df.groupby('Device_ID')['Temperature'].mean().idxmax()

'DEV_004'

19. Create a Battery_Status column:
Battery Status
>= 50 Healthy
20–49 Moderate
<20 Critical

In [46]:
df['Battery_Status'] = 'Healthy'

for i in range(len(df)):
    if df.loc[i, 'Battery_Level'] < 20:
        df.loc[i, 'Battery_Status'] = 'Critical'
    elif df.loc[i, 'Battery_Level'] < 50:
        df.loc[i, 'Battery_Status'] = 'Moderate'
    else:
        df.loc[i, 'Battery_Status'] = 'Healthy'

df['Battery_Status'].unique()
df[['Battery_Level', 'Battery_Status']].head(10)

       Battery_Level Battery_Status
3149           99.73        Healthy
13592          50.16        Healthy
16379          63.12        Healthy
1204           71.38        Healthy
13102          66.31        Healthy
5786           29.50       Moderate
2107           62.40        Healthy
9195           12.73       Critical
5375           85.74        Healthy
19403          49.87       Moderate

In [48]:
#20. Create a Temperature_Status column.
df['Temperature_Status'] = 'Normal'

for i in range(len(df)):
    if df.loc[i, 'Temperature'] > 75:
        df.loc[i, 'Temperature_Status'] = 'VeryHigh'
    elif df.loc[i, 'Temperature'] > 60:
        df.loc[i, 'Temperature_Status'] = 'High'
    elif df.loc[i, 'Temperature'] < 10:
        df.loc[i, 'Temperature_Status'] = 'Low'
    else:
        df.loc[i, 'Temperature_Status'] = 'Normal'

df['Temperature_Status'].unique()
df[['Temperature', 'Temperature_Status']].head(10)

       Temperature Temperature_Status
3149         50.97             Normal
13592        67.31               High
16379        78.07           VeryHigh
1204         70.26               High
13102        79.59           VeryHigh
5786         66.77               High
2107         79.23           VeryHigh
9195         59.27             Normal
5375         74.80               High
19403        69.13               High

In [50]:
print(df['Vibration'].max())
print(df['Vibration'].min())
print(df['Vibration'].mean())
print(df['Vibration'].median())

19.993705046847772
-0.48
2.5348028499091857
2.52

In [51]:
#21. Create a Vibration_Status column.
df['Vibration_Status'] = 'Normal'

for i in range(len(df)):
    if df.loc[i, 'Vibration'] > 10:
        df.loc[i, 'Vibration_Status'] = 'VeryHigh'
    elif df.loc[i, 'Vibration'] > 6:
        df.loc[i, 'Vibration_Status'] = 'High'
    elif df.loc[i, 'Vibration'] < 1:
        df.loc[i, 'Vibration_Status'] = 'Low'
    else:
        df.loc[i, 'Vibration_Status'] = 'Normal'

df['Vibration_Status'].unique()
df[['Vibration', 'Vibration_Status']].head(10)

       Vibration Vibration_Status
3149        1.94           Normal
13592       2.48           Normal
16379       2.86           Normal
1204        3.20           Normal
13102       2.04           Normal
5786        2.01           Normal
2107        2.54           Normal
9195        2.44           Normal
5375        2.70           Normal
19403       3.17           Normal

22. Create an overall Machine_Health column:
Normal
Warning
Critical

In [52]:
#Create an overall Machine_Health column:
df['Machine_Health'] = 'Normal'
for i in range(len(df)):
    if  df.loc[i, 'Temperature_Status'] == 'VeryHigh' or df.loc[i, 'Vibration_Status'] == 'VeryHigh':
        df.loc[i, 'Machine_Health'] = 'Critical'
    elif df.loc[i, 'Temperature_Status'] == 'High' or df.loc[i, 'Vibration_Status'] == 'High':
        df.loc[i, 'Machine_Health'] = 'Moderate'
    else:
        df.loc[i, 'Machine_Health'] = 'Normal'

df['Machine_Health'].unique()
df[['Temperature_Status', 'Vibration_Status', 'Machine_Health']].head(10)

      Temperature_Status Vibration_Status Machine_Health
3149              Normal           Normal         Normal
13592               High           Normal       Moderate
16379           VeryHigh           Normal       Critical
1204                High           Normal       Moderate
13102           VeryHigh           Normal       Critical
5786                High           Normal       Moderate
2107            VeryHigh           Normal       Critical
9195              Normal           Normal         Normal
5375                High           Normal       Moderate
19403               High           Normal       Moderate

In [53]:
#23. Find devices that have experienced critical conditions more than five times.
critical_devices = df[df['Machine_Health'] == 'Critical']
critical_devices.groupby('Device_ID').size()[critical_devices.groupby('Device_ID').size() > 5]

Device_ID
DEV_001    666
DEV_002    686
DEV_003    633
DEV_004    671
DEV_005    662
DEV_006    632
DEV_007    640
DEV_008    691
dtype: int64

In [58]:
#24. Find the factory with the highest number of abnormal sensor readings.
abnormal_readings = df[(df['Temperature_Status'] == 'VeryHigh') | (df['Vibration_Status'] == 'VeryHigh')]
abnormal_readings.groupby('Device_ID').size().idxmax()

'DEV_008'

In [59]:
df['Machine_Status'].unique()

array(['Normal', 'Warning', 'Critical'], dtype=object)

In [65]:
#25. Calculate the percentage of time each device operates under warning/critical conditions.
warning_critical_devices = df[(df['Machine_Status'].astype(str) == "Warning") | (df['Machine_Status'].astype(str) == "Critical")]
warning_critical_devices.groupby('Device_ID').size()/len(df) * 100

Device_ID
DEV_001    2.580
DEV_002    2.470
DEV_003    2.500
DEV_004    2.445
DEV_005    2.725
DEV_006    2.530
DEV_007    2.595
DEV_008    2.805
dtype: float64

In [66]:
#26. Identify the device that requires the highest maintenance priority.
maintenance_priority = df[df['Machine_Status'].astype(str) == "Critical"]
maintenance_priority.groupby('Device_ID').size().idxmax()

'DEV_007'